#멤버 정보 테이블
 CREATE TABLE SHOP_MEMBER (
 	MEM_ID VARCHAR(20) PRIMARY KEY #ID
 	, MEM_PW VARCHAR(20) NOT NULL #비번
 	, MEM_NAME VARCHAR(20) NOT NULL #이름
 	, MEM_TEL VARCHAR(15) #전화번호(배열)
 	, MEM_EMAIL VARCHAR(30) NOT NULL #이메일
 	, MEM_ADDR VARCHAR (20) NOT NULL #주소
 	, ADDR_DETAIL VARCHAR(20) #상세주소
  , PW_KEY INT REFERENCES forgotpw(PW_KEY) #비밀번호 찾기 질문 번호
  , PW_ANSWER VARCHAR(20) NOT NULL #비밀번호 찾기 질문 답변    
  , MEM_ROLE VARCHAR(14) NOT NULL DEFAULT 'USER'     #관리자는 ADMIN
  , JOIN_DATE DATETIME DEFAULT SYSDATE()
  );
	
	SELECT * FROM shop_member;
	
	-- SHOP_MEMBER 테이블에 컬럼 추가
ALTER TABLE SHOP_MEMBER ADD (
    STATUS VARCHAR(20) DEFAULT 'ACTIVE'  -- 'ACTIVE', 'WITHDRAWN', 'SUSPENDED'
);
 
 #상품정보
 CREATE TABLE ITEM (
 	ITEM_NUM INT PRIMARY KEY AUTO_INCREMENT #상품 번호
 	, ITEM_NAME VARCHAR(20) NOT NULL UNIQUE #상품명
 	, PRICE INT NOT NULL #가격
 	, ITEM_INTRO VARCHAR(500) #상품 소개
 	, PART VARCHAR(10) #부위
 	, REVIEW_AVG DOUBLE DEFAULT 0 #평균 평점
 	, ORIGIN VARCHAR(15) #원산지
 	, REG_DATE DATETIME DEFAULT SYSDATE() #상품 등록일
 );
 
CREATE TABLE ORDERS (
    -- 예: ORDER20231015001, payment-1697356800000
    ORDER_ID VARCHAR(100) PRIMARY KEY,
    
    -- 주문한 회원의 ID (회원 테이블과 연결)
    -- 예: user123, hong@email.com
    -- 외래키: members 테이블의 member_id를 참조
    MEM_ID VARCHAR(50) REFERENCES SHOP_MEMBER(MEM_ID),
    
    -- 주문한 상품명
    -- 예: "나이키 에어맥스", "아이폰 15 Pro"
    PRODUCT_NAME VARCHAR(200) NOT NULL,
    
    -- 총 주문 금액 (단위: 원)
    -- 예: 10000 = 10,000원
    TOTAL_AMOUNT INT NOT NULL,
    
    -- 주문 상태
    -- 예: PENDING(대기), PAID(결제완료), SHIPPING(배송중), 
    --     DELIVERED(배송완료), CANCELLED(취소)
    ORDER_STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    
    SHIPPING_REQUEST TEXT,
    
    -- 주문 생성 시간 (자동으로 현재 시간 입력)
    -- 예: 2023-10-15 14:30:25
    ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- 결제(Payment) 테이블
-- 실제 결제 처리 정보를 저장하는 테이블
-- 포트원 API로 받은 결제 정보를 저장
-- ============================================
CREATE TABLE PAYMENT (
    -- 결제 고유 식별자 (Primary Key, 포트원에서 발급)
    -- 예: imp_123456789012
    PAYMENT_ID VARCHAR(100) PRIMARY KEY,
    
    -- 어떤 주문에 대한 결제인지 연결 (orders 테이블과 연결)
    -- 한 주문당 하나의 결제
    ORDER_ID VARCHAR(100) REFERENCES ORDERS(ORDER_ID),
    
    -- 결제 수단
    -- 예: CARD(카드), VBANK(가상계좌), TRANS(실시간계좌이체), 
    --     PHONE(휴대폰), KAKAOPAY(카카오페이)
    PAYMENT_METHOD VARCHAR(20) NOT NULL,
    
    -- 결제 상태
    -- 예: READY(준비), PAID(결제완료), FAILED(결제실패), 
    --     CANCELLED(결제취소), REFUNDED(환불완료)
    PAYMENT_STATUS VARCHAR(20) NOT NULL DEFAULT 'READY',
    
    -- 실제 결제된 금액 (단위: 원)
    -- total_amount와 일치해야 함 (검증용)
    -- 예: 10000 = 10,000원
    PAID_AMOUNT INT NOT NULL,
    
    -- 결제 완료 시간
    -- 예: 2023-10-15 14:35:10
    PAID_AT TIMESTAMP
);
 
 #상품 이미지 테이블
 CREATE TABLE ITEM_itemIMG (
 	IMG_NUM INT PRIMARY KEY AUTO_INCREMENT
	, ORIGIN_IMG_NAME VARCHAR(100) #원본 파일명
	, ATTACHED_IMG_NAME VARCHAR(100) #첨부된 파일명
	, ITEM_NUM INT REFERENCES ITEM (ITEM_NUM) ON DELETE CASCADE #상품 번호
	, IS_MAIN VARCHAR(3) #메인이미지 : 'Y', 서브이미지 : 'N'
 );
 
 #평점 테이블
 CREATE TABLE REVIEW (
 	REVIEW_NUM INT PRIMARY KEY AUTO_INCREMENT #평점 번호
 	, RATING INT NOT NULL #별점
 	, TITLE VARCHAR(30) NOT NULL #제목
 	, MEM_ID VARCHAR(20) NOT NULL REFERENCES SHOP_MEMBER(MEM_ID) #회원 ID
 	, ITEM_NUM INT NOT NULL REFERENCES ITEM(ITEM_NUM) #상품 번호
 	, CONTENT VARCHAR(1000) NOT NULL #내용
 	, READ_CNT INT DEFAULT 0  #조회수
 	, CREATE_DATE DATETIME DEFAULT SYSDATE() #등록일
 ); 
  
 #평점 이미지 등록 테이블
 CREATE TABLE REVIEW_IMG (
 	REVIEW_IMG_NUM INT PRIMARY KEY AUTO_INCREMENT
	, REVIEW_ORIGIN_IMG_NAME VARCHAR(100) #원본 파일명
	, REVIEW_ATTACHED_IMG_NAME VARCHAR(100) #첨부된 파일명
	, REVIEW_NUM INT REFERENCES REVIEW (REVIEW_NUM) ON DELETE CASCADE #리뷰 번호
 );  
 
 #라즈베리파이 관리자 기능(온,습도 센서를 이용한 fan 액츄에이터 구현)
 CREATE TABLE FAN_FUNCTION (
 	THV_ID INT PRIMARY KEY AUTO_INCREMENT
 	, TEMPERATURE FLOAT  	
 	, HUMIDITY FLOAT 
 	, AIR_QUALITY INT 
 	, CREATE_DATE DATETIME DEFAULT SYSDATE()
 ); 
 
  #라즈베리파이 관리자 기능(조도센서를 이용한 LED 액츄에이터 구현)
 CREATE TABLE illuminance_function(
 	IM_ID INT PRIMARY KEY AUTO_INCREMENT
 	, ILLUMINANCE INT
 	, CREATE_DATE DATETIME DEFAULT SYSDATE()
 ); 
 
 #비밀번호 찾기용 질문 테이블
 CREATE TABLE forgotpw (
 PW_KEY INT PRIMARY KEY AUTO_INCREMENT #질문 번호
 , PW_QUESTION VARCHAR(50) NOT NULL #질문 내용 
 );  
 
 #장바구니 테이블 
 CREATE TABLE SHOP_CART(
  CART_NUM INT PRIMARY KEY AUTO_INCREMENT
  , ITEM_NUM INT REFERENCES ITEM(ITEM_NUM)
  , CART_CNT INT NOT NULL
  , MEM_ID VARCHAR(20) REFERENCES SHOP_MEMBER(MEM_ID)
  , TOTAL_PRICE INT NOT NULL
  , CART_DATE DATETIME DEFAULT SYSDATE()
 );
 
 #구매 테이블
 CREATE TABLE SHOP_BUY(
  BUY_NUM INT PRIMARY KEY AUTO_INCREMENT
  , ITEM_NUM INT REFERENCES ITEM(ITEM_NUM)
  , MEM_ID VARCHAR(20) REFERENCES SHOP_MEMBER(MEM_ID)
  , BUY_DATE DATETIME DEFAULT SYSDATE()
  , BUY_CNT INT #구매수량
  , ORDER_NUM INT #주문번호, 한 번에 여러 상품을 구매하면 동일한 주문번호를 가진다
 );
 
 #Q&A 테이블
 CREATE TABLE qna(
 	QNA_NUM INT PRIMARY KEY AUTO_INCREMENT
 	,	ITEM_NUM INT REFERENCES ITEM(ITEM_NUM)
 	,	MEM_ID VARCHAR(20) REFERENCES SHOP_MEMBER(MEM_ID)
 	,	QNA_DATE DATETIME DEFAULT SYSDATE()
 	,	CONTENT VARCHAR(300)
 ); 
 
 #답변 테이블
 CREATE TABLE reply(
 	REPLY_NUM INT PRIMARY KEY AUTO_INCREMENT
 	,	REPLY_MEM_ID VARCHAR(20) REFERENCES SHOP_MEMBER(MEM_ID)
 	,	QNA_NUM INT REFERENCES qna(QNA_NUM)
 	,	REPLY_DATE DATETIME DEFAULT SYSDATE()
 	,	REPLY_CONTENT VARCHAR(300)team_db
 ); 
 
 #회원탈퇴시 설문조사 테이블
 CREATE TABLE SURVEY(
 	NUM INT PRIMARY KEY AUTO_INCREMENT,
 	MEM_ID VARCHAR(20) REFERENCES SHOP_MEMBER(MEM_ID),
 	WITHDRAWAL VARCHAR(20),                        -- 탈퇴사유
 	REASON_UNCOMFORTABLE TEXT,            				 -- 불편했던 점
  	REASON_GOOD TEXT,                   				   -- 좋았던 점
  	REASON_IMPROVEMENT TEXT NOT NULL,							 -- 개선사항
 	DELETE_DATE DATETIME DEFAULT SYSDATE()         -- 탈퇴일
 );  
 
 #찜한 상품 테이블
 CREATE TABLE DIBS (
 	DIBS_NUM INT PRIMARY KEY AUTO_INCREMENT
 	, MEM_ID VARCHAR(20) REFERENCES shop_member(MEM_ID)
 	, ITEM_NUM INT REFERENCES item(ITEM_NUM)
 	, DIBS_DATE DATETIME DEFAULT SYSDATE()
 );
  
 #################################################
 ### 이 워크시트에 CREATE 문을 다 작성해주세요 ###


SELECT * FROM illuminance_function;
SELECT * FROM SHOP_MEMBER;
SELECT * FROM payment;